

exports.something = async (req, res) => {
    try {
        
    } catch (error) {
        res.status(500).json({ error: "Error logging in" });
    }
};
